doc-warnings: false
test-warnings: false
strictness: veryhigh
max-line-length: 120
uses:
  - flask
autodetect: true
requirements:
  - deps/core.txt
  - deps/test.txt
ignore-paths:
  - postman
  - lib
  - ks/docs
  - ks/docker_ks
python-targets:
  - 3